# -*- coding: utf-8 -*-
"""Fibonacci numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G80IkzDCaoMZZ3yfIud49JQJk6_zAeq1
"""

n=int(input("number of terms in the fibonnaci sequence-"))
a=0
b=1
print(a,b,end=' ')
for i in range(n-2):
  c=a+b
  print(c,end=' ')
  a=b
  b=c