# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jsgk8r7z_hIJmbF3pN8Eaf1QeH6ucdg8
"""

#Defining two sets
E={2,4,8,0,6}
N={2,4,1,3,5}

#UNION OF SETS
UNIONSET=E.union(N)
print("The union of E and N is",UNIONSET)

#INTERSECTION BETWEEN SETS
INTERSECTION=E.intersection(N)
print("The intersection of E and N is",INTERSECTION)

#DIFFERENCE BETWEEN E AND N
DIFFERENCE=E.difference(N)
print("The difference is ",DIFFERENCE)

#SYMMETRIC DIFFERENCE OF E AND N
SYMMETRIC_DIFFERENCE=E.symmetric_difference(N)
print("The symmetric difference is", SYMMETRIC_DIFFERENCE)